// UI
// export const SET_ERROR: 'UI/SET_ERROR' = 'UI/SET_ERROR'
// export const DISMISS_ERROR: 'UI/DISMISS_ERROR' = 'UI/DISMISS_ERROR'
export const SET_DRAWER_VIZ: 'UI/SET_DRAWER_VIZ' = 'UI/SET_DRAWER_VIZ'
