// @flow

// UI
// export const SET_ERROR: 'UI/SET_ERROR' = 'UI/SET_ERROR'
// export const DISMISS_ERROR: 'UI/DISMISS_ERROR' = 'UI/DISMISS_ERROR'
export const SET_DRAWER_VIZ: 'UI/SET_DRAWER_VIZ' = 'UI/SET_DRAWER_VIZ'

// Forecast
export const SET_FORECASTS: 'FORECAST/SET_FORECASTS' = 'FORECAST/SET_FORECASTS'
export const SET_TIMEOUT_ID: 'FORECAST/SET_TIMEOUT_ID' =
  'FORECAST/SET_TIMEOUT_ID'
export const SET_ACTIVE_CYCLE_FORECAST_ID: 'FORECAST/SET_ACTIVE_CYCLE_FORECAST_ID' =
  'FORECAST/SET_ACTIVE_CYCLE_FORECAST_ID'
export const SET_CYCLE_TIMEOUT_ID: 'FORECAST/SET_CYCLE_TIMEOUT_ID' =
  'FORECAST/SET_CYCLE_TIMEOUT_ID'
