export type WeatherCode =
  | 'freezing_rain_heavy'
  | 'freezing_rain'
  | 'freezing_rain_light'
  | 'freezing_drizzle'
  | 'ice_pellets_heavy'
  | 'ice_pellets'
  | 'ice_pellets_light'
  | 'snow_heavy'
  | 'snow'
  | 'snow_light'
  | 'flurries'
  | 'tstorm'
  | 'rain_heavy'
  | 'rain'
  | 'rain_light'
  | 'drizzle'
  | 'fog_light'
  | 'fog'
  | 'cloudy'
  | 'mostly_cloudy'
  | 'partly_cloudy'
  | 'mostly_clear'
  | 'clear' //
